name: Deployment

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: [ self-hosted ]
    environment: production
    steps:
      - name: deploy
        run: docker compose up -d
