name: Deployment

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: [ self-hosted ]
    environment: production
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: deploy
        run: docker-compose up -d
